#!/usr/bin/env bash
# Add these two lines to bashrc
STOW_FOLDERS="bin,screen,personal,tmux,vim,zsh"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
	echo "Installed $folder"
done
popd
